name: SCA Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # # Step 2: Debug requirements.txt
      # - name: Debug requirements.txt
      #   run: |
      #     if [ -f requirements.txt ]; then
      #       cat requirements.txt
      #     else
      #       echo "requirements.txt not found!"
      #       exit 1
      #     fi

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run Safety for SCA
      - name: Run Safety for SCA
        run: |
          pip install safety==1.10.3
          safety check --full-report --file=requirements.txt || { echo 'Safety check failed'; exit 1; }

      # Step 5: Install and run Pyraider for SCA
      - name: Install and run Pyraider
        run: |
          pip install pyraider
          pyraider --path . --output-format json --output-file pyraider_report.json || { echo 'Pyraider execution failed'; exit 1; }

      # Optional: Step 6: Upload Pyraider report as an artifact
      - name: Upload Pyraider Report
        uses: actions/upload-artifact@v3
        with:
          name: pyraider_report
          path: pyraider_report.json
